### ISSUE TITLE
[ERR 101] Invalid API Code or Invalid Signature

### ISSUE THREAD

**Issue by shirj** [joowani/quadriga#3]
Hi! 

First, thank you so much for doing this! This project is awesome. 

Second, I have been having issues using any functionality that requires authentication. Here is my code:

```python
import quadriga, sys
print(sys.version)

SECRET = 'b8thisismysecret1234567890abcdef'  # Not real secret, but same length, base 16 encoded string
KEY = 'ThisIsAKey' # Not real key, but same length, only upper and lower case letters

print('len(SECRET)==%d' % len(SECRET))
print('len(KEY)==%d' % len(KEY))

BOOK = 'eth_cad'
client = quadriga.QuadrigaClient(api_key=KEY, api_secret=SECRET, client_id='1', default_book=BOOK)

# Getting public data is fine
public_orders = client.get_public_orders(book=BOOK)
print(type(public_orders))

# But anything that requires authentication results in ERR 101
orders = client.get_orders(book=BOOK)
print(orders)
```

Output
```python
3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]

len(SECRET)==32
len(KEY)==10

<class 'dict'>

Traceback (most recent call last):
  File "C:/Users/Username/.spyder/qc/quadriga/main.py", line 19, in <module>
    orders = client.get_orders(book=BOOK)
  File "C:\Users\Username\.spyder\qc\quadriga\quadriga\__init__.py", line 175, in get_orders
    payload={'book': book}
  File "C:\Users\Username\.spyder\qc\quadriga\quadriga\rest_client.py", line 131, in post
    return self._handle_response(response)
  File "C:\Users\Username\.spyder\qc\quadriga\quadriga\rest_client.py", line 88, in _handle_response
    error_code=error_code
quadriga.exceptions.RequestError: [HTTP 200][ERR 101] Invalid API Code or Invalid Signature: ThisIsAKey
```

To be clear, when I replace the SECRET and KEY with my real ones, it results in the same error. 

I feel like this is potentially an issue on Quadriga's end as I couldn't get it to work with my own attempt at making a REST Client (in fact this is how I found this project :)), but it could be something else (maybe the signature generation?). Or is this an issue with my set up? I only set up the API keys a few hours ago so this may be the issue? 

Again, thanks for the awesome project!

**Comment by joowani** [comment]
Hi @shirj,

Just to double check, did you put in the correct client ID? This has to be the client ID that you use to log in to Quadriga CX website (I see that you are putting '1' in your example).

Thanks,
Joohwan

**Comment by joowani** [comment]
No problem! Let me know if you still have issues.
